version: "3"
services:
  node:
    image: "backend"
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    ports:
     - ${NODE_APP_PORT}:${NODE_APP_PORT}
