version: "3"
services:
  node:
    image: "backend"
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    ports:
     - 3001:3001
    volumes:
      - .:/app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=me@jeffkeith.me
      - PGADMIN_DEFAULT_PASSWORD=Meefer33!
    ports:
      - "8080:80"
    volumes:
      - ./pg-admin:/var/lib/pgadmin