version: "3"
services:
  node:
    image: "backend"
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    ports:
     - 3001:3001
    volumes:
      - .:/app
